version: '3.8'

services:
  # Host Application (Development Mode)
  host-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_DIRECTUS_API=${NEXT_PUBLIC_DIRECTUS_API}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME:-"Micro Frontend Dashboard"}
      - NEXT_PUBLIC_SITE_DESCRIPTION=${NEXT_PUBLIC_SITE_DESCRIPTION:-"A modern micro frontend architecture"}
      # Micro Frontend URLs
      - CHILD_APP_URL=http://localhost:3001
      - USER_MANAGEMENT_URL=http://localhost:3002
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - microfrontend-network

  # Development Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: microfrontend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - microfrontend-network

  # Development Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - microfrontend-network

networks:
  microfrontend-network:
    driver: bridge

volumes:
  postgres_dev_data: 
